/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "platform.h"
#define RCC_BASE				0x40021000
#define GPIO_BASE				0x40010800
#define RCC_APB2ENR				*(vuint32 *)(RCC_BASE +0x18)
#define GPIO_CRH				*(vuint32 *)(GPIO_BASE +0x04)
#define GPIO_ODR				*(vuint32 *)(GPIO_BASE +0x0C)

typedef union {
	vuint32 All_Fields;
	struct {
		vuint32 reserved:13;
		vuint32 PIN13:1;

	}pin;

}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIO_BASE + 0x0C);
int main(void)
{
    RCC_APB2ENR|=(1<<2);
    GPIO_CRH &=0xFF0FFFFF;
    GPIO_CRH |=0x00200000;
    while(1)
    {
    	R_ODR->pin.PIN13=1;
    	for(int i=0;i<5000;i++);
    	R_ODR->pin.PIN13=0;
    	for(int i=0;i<5000;i++);
    }

}
